### ISSUE TITLE
GoPaySDK keeps using the same login token

### ISSUE THREAD

**Issue by asaiasai** [gyro-n/gopay-java-sdk#16]
It looks like you can update the login token with the withLoginToken method.
https://github.com/gyro-n/gopay-java-sdk/blob/c90a01ea82467cb61c31f4961657f4f7f7773f82/src/main/java/com/univapay/gopay/GoPaySDK.java#L90

In practice, however, it is not updated in most cases.
This is because the setRetrofitOptions method is called only once.
https://github.com/gyro-n/gopay-java-sdk/blob/c90a01ea82467cb61c31f4961657f4f7f7773f82/src/main/java/com/univapay/gopay/GoPaySDK.java#L77

On the other hand, there is a problem that the setRetrofitOptions method is called in many places in the GoPaySDK class.
(When adding a new method, you must always call the setRetrofitOptions method!)

In order not to confuse SDK users, it is better to modify as follows.
1. Prepare three kinds of constructors for each authentication method. Set login tokens, application tokens and secrets within the constructors.
2. Delete the withLoginToken method and withAppTokenCredentials method.
3. Delete setRetrofitOptions method.

**Comment by justinian336** [comment]
This is a good suggestion, could you make a PR?
