### ISSUE TITLE
Doesn't URL encode search query parameters

### ISSUE THREAD

**Issue by shiraki-y** [gyro-n/gopay-java-sdk#48]
e.g.
can't search with letters which include "-"(hyphen)
Hyphen mark should be changed to "&#8208;" on the URL. 
But now it is not formatted so the searching doesn't work correctly.
(It is not the problem of encoding setting of `@Query`. There is some other cause.)

**Comment by shiraki-y** [comment]
For now, there doesn't seem to be any problems about this issue.

<Checked contents>

Percent encoding in the URL works correctly, such as: 
    Store name is "あいうえ店"
    Search parameter sent to SDK is "あ"
    -> The URL parameter is encoded by percent.
        The search result is correct.

Some characters which can transform to the character reference of HTML aren't changed, such as:
    Store name is "somewhere-store"
    Search parameter sent to SDK is "-" (hyphen)
    -> The URL parameter is not encoded.
        But the search result is correct.

**Comment by justinian336** [comment]
Let's close this issue for now and reopen it in case the bug shows up again.
