### ISSUE TITLE
Process can not be terminated by abandoned OkHttp thread?

### ISSUE THREAD

**Issue by t-nasu** [gyro-n/gopay-java-sdk#5]
Many charge creation seems to cause this problem.

Thread dump: [test60996.txt](https://github.com/gyro-n/gopay-java-sdk/files/1513881/test60996.txt)

**Comment by asaiasai** [comment]
調査しましたがまったく再現せず、原因が不明です。

BatchCreateCharge で1000件のチャージを作成しましたが、正常に作成されてプロセスも終了しました。

さらに多い件数（10000件など）で試すと処理時間が増加するため、トランザクショントークンの有効時間が5分間しかない関係上、一部またはすべてのチャージ作成に失敗しました。
（ですので、そもそも現実的な使い方ではなさそうです）
ただし、チャージ作成には失敗しましたがプロセスは正常に終了しました。

**Comment by t-nasu** [comment]
やはり再現するようです。Threaddumpを添付します。
BatchCreateChargeではなく、直接CreateCharegeを使っていて、Callbackを使用しているようです。

> さらに多い件数（10000件など）で試すと処理時間が増加するため、トランザクショントークンの有効時間が5分間しかない関係上、一部またはすべてのチャージ作成に失敗しました。

recurring tokenで試したらどうでしょうか？

**Comment by t-nasu** [comment]
[20171208_dump.txt](https://github.com/gyro-n/gopay-java-sdk/files/1547292/20171208_dump.txt)
[20171211_dump.txt](https://github.com/gyro-n/gopay-java-sdk/files/1547293/20171211_dump.txt)

**Comment by asaiasai** [comment]
BatchCreateChargeでrecuring tokenを使い、10000件のチャージが正常に作成できました。
また、直接CreateChargeを使い、コールバックを使用しましたが、同様に10000件のチャージが正常に作成できました。
プロセスも正常に終了しました。

口頭で伺った話では、RetrofitとOkHttpのバージョンを上げることで解決される可能性があるとのことでしたので、他に手がかりもない状況ですのでいったんそれを試してみます。

**Comment by justinian336** [comment]
この件は完全に解決されましたか？

**Comment by t-nasu** [comment]
#20 によって解決しました。
